/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rockpaperscissors;

import java.util.*;

/**
 *
 * @author Joshua Pregbaha
 */
public class RPS extends javax.swing.JFrame {
    
    String choice;
    String choice1;
    String alphabet = "RPS";
    Random rnd = new Random();
    Scanner scan = new Scanner(System.in);

    /**
     * Creates new form RPS
     */
    public RPS() {
        initComponents();
    }
    
    public void play() {
        char randomchar = alphabet.charAt(rnd.nextInt(alphabet.length()));
        String s = Character.toString(randomchar);
        //System.out.println(jXDatePicker1.getDate());
       // System.out.println(jXDatePicker1.getSelected);
        switch (choice) {
            case "R":
                yourChoice.setText("You chose Rock");
                break;
            case "P":
                yourChoice.setText("You chose Paper");
                break;
            case "S":
                yourChoice.setText("You chose Scissors");
                break;
            default:
                break;
        }

        switch (s) {
            case "R":
                compChoice.setText("Computer chose Rock");
                break;
            case "P":
                compChoice.setText("Computer chose Paper");
                break;
            case "S":
                compChoice.setText("Computer chose Scissors");
                break;
            default:
                break;
        }

        if (choice.equals(s)) {
            answer.setText("Draw. Nobody wins");
        } else if (choice.equals("R") && s.equals("P")) {
            answer.setText("Computer wins");
        } else if (choice.equals("R") && s.equals("S")) {
            answer.setText("You win!");
        } else if (choice.equals("P") && s.equals("R")) {
            answer.setText("You win!");
        } else if (choice.equals("P") && s.equals("S")) {
            answer.setText("Computer wins");
        } else if (choice.equals("S") && s.equals("R")) {
            answer.setText("Computer wins");
        } else if (choice.equals("S") && s.equals("P")) {
            answer.setText("You win!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SCISSORS = new javax.swing.JButton();
        PAPER = new javax.swing.JButton();
        ROCK = new javax.swing.JButton();
        compChoice = new javax.swing.JTextField();
        answer = new javax.swing.JTextField();
        yourChoice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock Paper Scissors");

        SCISSORS.setText("SCISSORS");
        SCISSORS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SCISSORSActionPerformed(evt);
            }
        });

        PAPER.setText("PAPER");
        PAPER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAPERActionPerformed(evt);
            }
        });

        ROCK.setText("ROCK");
        ROCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROCKActionPerformed(evt);
            }
        });

        yourChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yourChoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ROCK, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PAPER, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(SCISSORS, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yourChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SCISSORS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAPER, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ROCK, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(yourChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(compChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SCISSORSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SCISSORSActionPerformed
        // TODO add your handling code here:
        choice = "S";
        play();
    }//GEN-LAST:event_SCISSORSActionPerformed

    private void PAPERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAPERActionPerformed
        // TODO add your handling code here:
        choice = "P";
        play();
    }//GEN-LAST:event_PAPERActionPerformed

    private void ROCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROCKActionPerformed
        // TODO add your handling code here:
        choice = "R";
        play();
    }//GEN-LAST:event_ROCKActionPerformed

    private void yourChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yourChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yourChoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PAPER;
    private javax.swing.JButton ROCK;
    private javax.swing.JButton SCISSORS;
    private javax.swing.JTextField answer;
    private javax.swing.JTextField compChoice;
    private javax.swing.JTextField yourChoice;
    // End of variables declaration//GEN-END:variables
}
